---
- url_slug: charte-18encommun
  settings:
    call_to_action_text: Cliquez sur une image pour interpeller un des candidats Ã 
      la Mairie de Paris sur Twitter
    cause_name: charte-18encommun
    custom_text: >
      <p>La dÃ©mocratie participative est brandie par les candidats et maires
      en exercice depuis de nombreuses annÃ©es comme Ã©tendard de leur politique publique.
      Cependant, des conseils de quartier jusquâ€™aux consultations locales, peu de
      moyens sont mis Ã  disposition, lâ€™information fait dÃ©faut, et les groupes de
      travail sont socialement homogÃ¨nes. Des villes comme Barcelone, Madrid, ou Saillans
      dans la drÃ´me font bien mieux et regorgent dâ€™inventivitÃ©. En consÃ©quence, les
      villes sâ€™en retrouvent transformÃ©es. Ne faisons pas de la dÃ©mocratie Participative
      un simple concept marketing !<br />
      <br />
      Le mouvement â€œ18 en communâ€, apartisan et inclusif <a href="http://18encommun.fr/la-charte/">propose une
      charte de la participation citoyenne</a>. Cette charte nâ€™est pas exhaustive,
      mais permet dâ€™engager les candidats dans un effort qui sera surveillÃ© par les
      citoyens et les administrÃ©s.<br />
      <br />
      Interpellons les candidat.e.s Ã  la mairie de Paris Ã  sâ€™engager Ã  signer la charte de participation citoyenne,
      et montrons notre soutien Ã  ces mesures afin que leur engagement ne soit pas ignorÃ©.<br />
      <br />
      <a href="https://municipales-citoyennes.wesign.it/fr">Signez la pÃ©tition pour la Charte de la participation citoyenne inclusive !</a>
      <br />
      </p>
    description: Le 18 en Commun propose la charte de la participation inclusive
    hero_text: >
      Nous voulons de <a href="http://18encommun.fr/la-charte/">vraies mesures</a>
      pour la dÃ©mocratie participative !
    redirect_uri: https://charteparticipationcitoyenneinclusive.wesign.it/fr
    tags: "#municipalisme #democratieparticipative #paris18"
    targeted_demographics: Candidats Ã  la Mairie de Paris
    title: Nous voulons de vraies mesures pour la dÃ©mocratie participative !
    tweet_format: >
        Nous voulons de vraies mesures pour la #DÃ©mocratieParticipative ! %1$s signez la charte de participation citoyenne et communiquez votre dÃ©sir dâ€™amÃ©liorer la vie dÃ©mocratique de votre ville #MunicipalesCitoyennes https://municipales-citoyennes.wesign.it/fr via - @WeSignit

- url_slug: extraordener
  settings:
    call_to_action_text: Cliquez sur une image pour interpeller un des candidats aux
      municipales Ã  Paris sur Twitter
    cause_name: extraordener
    custom_text: >
        <h1>Pour un grand espace vert et solidaire : un parc Extra-Ordener</h1>
        <p>Dans le 18e arrondissement de Paris, l'un des moins verts et des plus denses de Paris, se trouve une friche SNCF grande comme 5 terrains de foot. Les promoteurs et la mairie actuelle veulent y construire un grand complexe bureaux + logements : tours de 10 Ã©tages, parking, data-center, commerces haut de gamme... Et au centre, un jardinet pour faire bonne mesure. Ce projet est Ã  rebours des besoins de notre quartier populaire et de l'urgence Ã©cologique.<br><br>
        Contre le rÃ©chauffement climatique et la pollution de l'air, pour amÃ©liorer notre santÃ© et que la jeunesse du 18Ã¨me respire enfin, aidez-nous Ã  obtenir un grand parc central en pleine terre Ã  Ordener-Poissonniers.<br><br>
        Interpellons les candidat.e.s aux municipales pour quâ€™ils.elles mettent un terme Ã  ce projet inutile !</p><br><br>
        <a href="https://unparcextraordener.wesign.it/fr">Pour un Paris qui respire ! Signez notre pÃ©tition.</a>
    description: collectif pour un parc extraordener
    hero_text: Les citoyen.ne.s rÃ©clament un parc central dans le 18Ã¨me !
    redirect_uri: https://unparcextraordener.wesign.it/fr
    tags: "#ecologie #paris18 #fricheordener"
    targeted_demographics: Candidats aux municipales Ã  Paris
    title: Les citoyen.ne.s rÃ©clament un parc central dans le 18Ã¨me !
    tweet_format: >
          .%1$s Les quartiers populaires aussi ont le droit de respirer !
          Le 18Ã¨me rÃ©clame son grand parc central, en pleine terre et accessible Ã  tout.e.s.
          #UnParcExtraOrdener #UnParcPourLe18Ã¨me https://unparcextraordener.wesign.it/fr"

- url_slug: je-ne-suis-pas-un-heros
  settings:
    call_to_action_text: Cliquez sur l'image pour interpeller Emmanuel Macron sur twitter
    cause_name: "#JeNeSuisPasUnHeros"
    custom_text: >
        <p><strong>Vous avez signÃ© laÂ <a href="https://confinesmobilises.wesign.it/fr">pÃ©tition de la campagne #JeNeSuisPasUnHÃ©ros</a>.</strong>Â Â PortÃ©e par des collectifs inter-hÃ´pitaux, scientifiques et citoyens, elle exige du matÃ©riel de protection complet pour les personnels hospitaliers, des embauches, des hausses de salaires, la fin de la T2A, le retrait du plan dâ€™Ã©conomie de 4 milliards dâ€™euros dans le secteur de la santÃ©.Â </p> <p><strong>Il est temps aujourd'hui d'interpeler massivement notre prÃ©sident de la rÃ©publiqueÂ </strong>afin qu'il annonce un programme de mesures Ã  la hauteur de ces enjeuxÂ </p>
    description: "#JeNeSuisPasUnhÃ©ros : Covid-19, Sauvons l'hÃ´pital public"
    hero_text: "Coronavirus: Des mesures concrÃ¨tes pour lâ€™hÃ´pital public!"
    redirect_uri: https://confinesmobilises.wesign.it/fr
    tags: "Coronavirus, covid-19, hÃ´pital Public"
    title: Interpellons le PrÃ©sident de la rÃ©publique pour sauver l'hÃ´pital public
    targeted_demographics: Emmanuel Macron, PrÃ©sident de la RÃ©publique
    tweet_format: >
        . "%1$s" Les personnels hÃ´spitaliers ne sont pas des hÃ©ros, mais payent les consÃ©quences d'un systÃ¨me de santÃ© dÃ©gradÃ©. Nous voulons de vraies mesures pour l'hÃ´pital public #JeNesuisPasUnHÃ©ros #COVID19fr via - @WeSignit >>> https://confinesmobilises.wesign.it/fr

- url_slug: confines-dehors
  settings:
    call_to_action_text: Cliquez sur l'image pour interpeller le Ministre du Logement Julien Denormandie sur twitter
    cause_name: "#ConfinÃ©sDehors"
    custom_text: >
        <p><strong>Vous avez signÃ© <a href="https://confine-dehors.wesign.it/fr">la pÃ©tition pour la rÃ©quisition des logements</a>, car prÃ¨s de 200 000 personnes vivent aujourd'hui sans abri&nbsp;</strong>. Pendant cette pÃ©riode de crise le gouvernement a fait quelques rÃ©quisitions d'hÃ´tels, mais cela est loin d'Ãªtre suffisant. </p> <p>Pour leur santÃ© et la santÃ© de toutes et tous, le prÃ©sident de la RÃ©publique, le gouvernement et les maires des grandes villes doivent prendre immÃ©diatement toutes les dispositions nÃ©cessaires pour <strong>rÃ©quisitionner les logements vacants ainsi que les logements touristiques louÃ©s sur des plateformes de type Airbnb</strong></p>
    description: "#ConfinÃ©sdehors: RÃ©quisition des logements vides pour reloger les sans-abri"
    hero_text: "Coronavirus: Demandons au ministre du logement la rÃ©quisition des logements pour les sans abris !"
    redirect_uri: https://confine-dehors.wesign.it/fr
    targeted_demographics: Julien Denormandie, Ministre du Logement
    tags: "Sdf, logement, Airbnb, coronavirus, covid19"
    title: Interpellons le Ministre du Logement pour reloger les SDF
    tweet_format: >
        . "%1$s" Vos mesures ne sont pas suffisantes. RÃ©quisitionnez des logements vacants et des appartements louÃ©s sur les plateformes comme #Airbnb pour reloger immÃ©diatement tous les sans-abri. #SDF #ConfinÃ©sDehors - via @WeSignit ğŸ‘‰ğŸ‘‰https://confine-dehors.wesign.it/fr

